### ISSUE TITLE
SECP256K1

### ISSUE THREAD

**Issue by shaft45** [Emill/P256-Cortex-M4#2]
Hi Emill,
Amazing work ! The performance is insane.
Sorry if my question is absurd, how can i change the curve for using SECP256K1 ?
Many thanks !

**Comment by Emill** [comment]
Hi and thank you!

Due to the optimized assembly made specifically for this curve, it's not a trivial change. You would have to modify the field arithmetic functions to reduce with the prime for that curve. You would also need to change the functions that reduce using the curve order, modify all precomputed curve points and so on. So you really need to know assembly as well as what you're doing to do this...

**Comment by shaft45** [comment]
Thanks for your response :)
I suspected that it would be difficult to modify the curve.
Many thanks !

**Comment by shaft45** [comment]
Hello Emill,
I'm trying to undrestand precomputed points, but it's to "hard" for my knowleadge :(
Any chance to have help if you got time ?
Many thanks :)

**Comment by Emill** [comment]
Are there any specific precomputed points you mean? Different algorithms use different precomputed points.

**Comment by shaft45** [comment]
Thanks Emill !
I think i'm not competent enough to understand mathematical optimizations.
Do you think you can make this change in the future?

**Comment by Emill** [comment]
Introducing secp256k1 is of course possible, but like 90% of the code would need to be rewritten. The high level algorithms could stay the same though. This is not something I'm currently planning to do unless I get a good job offer for it I think.

**Comment by shaft45** [comment]
I understand, i'm student i haven't enought, but what should be good job offer for you ;)
